### ISSUE TITLE
Syntax Error in deploy-apps.sh

### ISSUE THREAD

**Issue by jbhardman** [bpschmitt/offsite-k8s-workshop#3]
I believe there is a syntax error in the `sed` command in the deploy-apps.sh script.

It's trying to replace the REPLACE_ME with the name of my app from input, but it fails because there is a set of double quotes right in front of the find/replace string. The double quotes are empty. When I removed those quotes, sed then did its job properly.

**Comment by bpschmitt** [comment]
Fixed. Thanks for catching this!.
